name: yarzawin-dev
services:
  yarzawin-postgres:
    container_name: yarzawin-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  yarzawin-api:
    build:
      context: ../apps/yarzawin-api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../apps/yarzawin-api:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: yarzawin-postgres
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - yarzawin-postgres

  yarzawin-web:
    build:
      context: ../apps/yarzawin-web
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../apps/yarzawin-web:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '3010:3010'
    depends_on:
      - yarzawin-api

volumes:
  postgres_data:
